name: Build and Push Image

on: 
    push:
    
    workflow_dispatch:
    

jobs:
    build-image-push:
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v3
      
            - name: Log in to Docker Hub
              env:
                  username: ${{ secrets.DOCKER_USER }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
              run: |
                  docker login hub.docker.com -u ${username} -p {password}
      
            - name: Build Docker image
              run: |
                  docker build --tag=rakshs/ghaction:$(date + %s)
            - name: Push docker image
              run: docker push ${{ secrets.DOCKER_USER }}/ghaction
