name: Build and Push Image

on: 
    push:
    
    workflow_dispatch:
    

jobs:
    build-image-push:
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v3
            - name: echo secrets
              run: |
                  echo User ${{ secrets.DOCKER_USER }}   
                  echo Pwd ${{ secrets.DOCKER_PASSWORD }}
            - name: Log in to Docker Hub by Action
              uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
              with:
                  username: ${{ secrets.DOCKER_USER }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
      
            - name: Log in to Docker Hub
              env:
                  username: ${{ secrets.DOCKER_USER }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
              run: |
                  echo ${username}   
                  echo ${password}
                  docker login -u ${username} -p {password}
      
            - name: Build Docker image
              run: |
                  docker build --tag=rakshs/ghaction:$(date + %s)
            - name: Push docker image
              run: docker push ${{ secrets.DOCKER_USER }}/ghaction
