name: Build and Push Image

on: 
    workflow_dispatch:
    

jobs:
    build-image-push:
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v3

            - name: Log in to Docker Hub by Action
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_USER }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
                  
            - name: Build and push Docker image
              uses: docker/build-push-action@v3
              with:
                  context: .
                  tags: rakshs/ghaction:alpha
                  push: true
                  build-args: |
                      SFDBUNAME=${{secrets.SFDBUNAME}}
                      SFDBPWD=${{secrets.SFDBPWD}}
