name: Multi Repo Setup

on: 
    workflow_dispatch:
    

jobs:
    test-python-setup:
        runs-on: ubuntu-latest
        steps:
            - name: Check out the first repo
              uses: actions/checkout@v3
            - name: Check out the second repo
              uses: actions/checkout@v3
              with:
                  repository: 'Git-Beginner/module-json'
                  ref: 'master'
                  path: $HOME/module
            - name: validate.
              run: |
                  pwd
                  ls
                  cd $HOME/module
                  pwd
                  ls
            - uses: actions/setup-python@v4
              with:
                python-version: '3.9'
                cache: 'pip' # caching pip dependencies
            - run: |
                echo pwd
